- block:
  - name: Build uriel image and push it to DockerHub
    docker_image:
      path: "{{ playbook_dir }}/../../../judgels-backends/uriel/uriel-dist"
      name: judgels/uriel
      force: yes
      push: yes
      buildargs:
        VCS_REF: "{{ lookup('env', 'GITHUB_SHA') }}"
