language: java

jdk:
  - oraclejdk8

install:
  - git clone https://github.com/judgels/commons.git ../commons
  - git clone https://github.com/judgels/judgels.git ../judgels

script:
  - ../judgels/scripts/download-activator.sh
  - export PATH=$PATH:~/activator
  - activator test

