- block:
  - name: Create jophiel container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/jophiel/var
      - /judgels/jophiel/var/conf

  - name: Generate jophiel config
    template:
      src: "{{ playbook_dir }}/../conf/jophiel.yml.j2"
      dest: /judgels/jophiel/var/conf/jophiel.yml
      mode: '0644'

  - name: Pull jophiel image
    docker_image:
      name: ghcr.io/ia-toki/judgels/jophiel
      tag: "{{ judgels_version | default('latest', true) }}"
      source: pull
      force_source: yes

  - name: Run a jophiel container to do db migration
    docker_container:
      name: jophiel-migrate
      image: "ghcr.io/ia-toki/judgels/jophiel:{{ judgels_version | default('latest', true) }}"
      restart: yes
      network_mode: host
      volumes:
        - "/judgels/jophiel/var:/judgels/jophiel/var"
      command: dbMigrate
