- block:
  - name: Create jophiel container mount volume
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      mode: "0777"
    with_items:
      - /judgels/jophiel/var
      - /judgels/jophiel/var/conf

  - name: Generate jophiel config
    template:
      src: "{{ playbook_dir }}/../../../deployment-repo/conf/jophiel.yml"
      dest: /judgels/jophiel/var/conf/jophiel.yml

  - name: Pull jophiel image
    docker_image:
      name: judgels/jophiel
      tag: "{{ judgels_version | default('latest', true) }}"
      force: yes

  - name: Run a jophiel container to do db migration
    docker_container:
      name: jophiel-migrate
      image: "judgels/jophiel:{{ jophiel_version | default('latest', true) }}"
      restart: yes
      network_mode: host
      volumes:
        - "/judgels/jophiel/var:/judgels/jophiel/var"
      command: dbMigrate

  tags:
    - jophiel-migrate
