- block:
  - name: Create sandalphon container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/sandalphon/var
      - /judgels/sandalphon/var/conf
      - /judgels/sandalphon/var/data

  - name: Generate sandalphon config
    template:
      src: "{{ playbook_dir }}/../conf/sandalphon.conf.j2"
      dest: /judgels/sandalphon/var/conf/sandalphon.conf

  - name: Pull sandalphon image
    docker_image:
      name: docker.pkg.github.com/ia-toki/judgels/sandalphon
      tag: "{{ judgels_version | default('latest', true) }}"
      force: yes

  - name: Run a sandalphon container
    docker_container:
      name: sandalphon
      image: "docker.pkg.github.com/ia-toki/judgels/sandalphon:{{ judgels_version | default('latest', true) }}"
      restart: yes
      restart_policy: always
      log_driver: json-file
      log_options:
        max-size: 256m
        max-file: "2"
      network_mode: host
      volumes:
        - "/judgels/sandalphon/var:/judgels/sandalphon/var"
      env:
        JAVA_OPTS: "-Xmx{{ sandalphon_xmx }}"
        MAIN_OPTS: "-Dhttp.port=9002 -Dconfig.file=/judgels/sandalphon/var/conf/sandalphon.conf -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/judgels/sandalphon/var/log"

  - name: Allow Sandalphon traffic through the firewall
    ufw:
      rule: allow
      to_port: 9002
      proto: tcp
      comment: Judgels Sandalphon
