- block:
  - name: Create raphael container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/raphael/var
      - /judgels/raphael/var/conf

  - name: Generate raphael config
    template:
      src: "{{ playbook_dir }}/../conf/raphael.js.j2"
      dest: /judgels/raphael/var/conf/raphael-v8.js
      mode: '0644'

  - name: Pull raphael image
    docker_image:
      name: ghcr.io/ia-toki/judgels/raphael
      tag: "{{ judgels_version | default('latest', true) }}"
      source: pull
      force_source: yes

  - name: Run a raphael container
    docker_container:
      name: raphael
      image: "ghcr.io/ia-toki/judgels/raphael:{{ judgels_version | default('latest', true) }}"
      restart: yes
      restart_policy: always
      log_driver: json-file
      log_options:
        max-size: 256m
        max-file: "2"
      ports:
        - "{{ raphael_port | default('5000', true) }}:5000"
      volumes:
        - "/judgels/raphael/var:/judgels/raphael/var"

  - name: Allow raphael traffic through the firewall
    ufw:
      rule: allow
      to_port: "{{ raphael_port | default('5000', true) }}"
      proto: tcp
      comment: judgels raphael
