- block:
  - name: Build jerahmeel image and push it to DockerHub
    docker_image:
      path: "{{ playbook_dir }}/../../../judgels-legacy/jerahmeel"
      name: judgels/jerahmeel
      force: yes
      push: yes

  - name: Tag jerahmeel latest version
    docker_image:
      name: judgels/jerahmeel:latest
      repository: "judgels/jerahmeel:{{ judgels_version }}"
      force: yes
      pull: no
      push: yes
      state: present
    when: judgels_version is defined
