- block:
  - name: Create uriel container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/uriel/var
      - /judgels/uriel/var/conf
      - /judgels/uriel/var/data

  - name: Generate uriel config
    template:
      src: "{{ playbook_dir }}/../conf/uriel.yml.j2"
      dest: /judgels/uriel/var/conf/uriel.yml
      mode: '0644'

  - name: Generate uriel launcher config
    template:
      src: "{{ playbook_dir }}/../conf/uriel-launcher.yml.j2"
      dest: /judgels/uriel/var/conf/launcher-custom.yml
      mode: '0644'

  - name: Pull uriel image
    docker_image:
      name: judgels/uriel
      tag: "{{ judgels_version | default('latest', true) }}"
      source: pull
      force_source: yes

  - name: Run a uriel container
    docker_container:
      name: uriel
      image: "judgels/uriel:{{ judgels_version | default('latest', true) }}"
      restart: yes
      restart_policy: always
      log_driver: json-file
      log_options:
        max-size: 256m
        max-file: "2"
      network_mode: host
      volumes:
        - "/judgels/uriel/var:/judgels/uriel/var"

  - name: Allow uriel traffic through the firewall
    ufw:
      rule: allow
      to_port: "9004"
      proto: tcp
      comment: judgels uriel
