- block:
  - name: Generate raphael config
    template:
      src: "{{ playbook_dir }}/../conf/raphael.js.j2"
      dest: /judgels/raphael/var/conf/raphael-v8.js
      mode: '0644'

  - name: Restart raphael
    docker_container:
      name: raphael
      restart: yes
