judgels_mode: JUDGELS
judgels_name: Judgels
judgels_slogan: Judgment Angels
judgels_title: Competitive Programming Platform
judgels_description: Welcome to Judgels
judgels_scheme: https

###################################################################################################

letsencrypt_email: xxx@yyy.com

###################################################################################################

db_root_home: /root
db_root_password: xxx
db_host: localhost
db_username: xxx
db_password: xxx
db_options: "?useSSL=false"

###################################################################################################

raphael_url: judgels.com
sandalphon_url: sandalphon.judgels.com
judgels_api_url: api.judgels.com
jophiel_url: api.judgels.com
uriel_url: api.judgels.com
jerahmeel_url: api.judgels.com
rabbitmq_mgmt_url: rabbitmq.judgels.com

###################################################################################################

michael_xmx: 1g
jophiel_xmx: 1g
sandalphon_xmx: 1g
uriel_xmx: 1g
jerahmeel_xmx: 1g
gabriel_xmx: 1g

###################################################################################################

recaptcha_siteKey: xxx
recaptcha_secretKey: xxx

###################################################################################################

googleAnalytics_trackingId: xxx

###################################################################################################

jophiel_auth_google_clientId: xxx

jophiel_aws_accessKey: xxx
jophiel_aws_secretKey: xxx
jophiel_aws_s3BucketRegionId: ap-southeast-1
jophiel_aws_cloudFrontBaseUrl: https://xxx.cloudfront.net

jophiel_mailer_host: smt.mailtrap.io
jophiel_mailer_port: 2525
jophiel_mailer_useSsl: false
jophiel_mailer_username: xxx
jophiel_mailer_password: xxx
jophiel_mailer_sender: xxx@yyy.com

jophiel_userAvatar_fs_type: local
jophiel_userAvatar_fs_s3BucketName: xxx
jophiel_userRegistration_enabled: false
jophiel_userRegistration_useRecaptcha: false
jophiel_userRegistration_activationEmailTemplate_subject: xxx
jophiel_userRegistration_activationEmailTemplate_body: xxx
jophiel_userResetPassword_enabled: false
jophiel_userResetPassword_requestEmailTemplate_subject: xxx
jophiel_userResetPassword_requestEmailTemplate_body: xxx
jophiel_userResetPassword_resetEmailTemplate_subject: xxx
jophiel_userResetPassword_resetEmailTemplate_body: xxx

jophiel_superadminCreator_initialPassword: xxx

jophiel_session_maxConcurrentSessionsPerUser: -1
jophiel_session_disableLogout: false

###################################################################################################

sandalphon_play_crypto_secret: xxx
sandalphon_uriel_secret: xxx
sandalphon_jerahmeel_secret: xxx
sandalphon_gabriel_secret: xxx

###################################################################################################

uriel_aws_accessKey: xxx
uriel_aws_secretKey: xxx
uriel_aws_s3BucketRegionId: ap-southeast-1

uriel_submission_fs_type: local
uriel_submission_fs_s3BucketName: xxx
uriel_file_fs_type: local
uriel_file_fs_s3BucketName: xxx

###################################################################################################

jerahmeel_aws_accessKey: xxx
jerahmeel_aws_secretKey: xxx
jerahmeel_aws_s3BucketRegionId: ap-southeast-1

jerahmeel_play_crypto_secret: jxxx
jerahmeel_submission_fs_aws: false

jerahmeel_submission_fs_type: local
jerahmeel_submission_fs_s3BucketName: xxx

###################################################################################################

gabriel_grading_numWorkerThreads: 2

###################################################################################################

rabbitmq_host: localhost
rabbitmq_username: guest
rabbitmq_password: guest

###################################################################################################

scoreboard_receiver_secret: xxx
scoreboard_server_secret: xxx

###################################################################################################

dump_dir: "{{ inventory_dir }}/dump"
