judgels_version: latest
judgels_name: Judgels
judgels_slogan: Judgment Angels
judgels_title: Competitive Programming Platform
judgels_description: Welcome to Judgels
judgels_scheme: https
judgels_scheme_internal: http


letsencrypt_email: xxx@yyy.com


dockerhub_username: xxx
dockerhub_email: xxx@yyy.com
dockerhub_token: xxx


db_root_home: /root
db_root_password: xxx
db_host: localhost
db_username: xxx
db_password: xxx
db_options: "?useSSL=false"


raphael_url: judgels.com
jophiel_url: jophiel.judgels.com
sandalphon_url: sandalphon.judgels.com
uriel_url: uriel.judgels.com
rabbitmq_mgmt_url: rabbitmq.judgels.com


jophiel_url_internal: localhost:9001
sandalphon_url_internal: localhost:9002
sealtiel_url_internal: localhost:9003
uriel_url_internal: localhost:9004


aws_accessKey: xxx
aws_secretKey: xxx
aws_s3BucketRegionId: ap-southeast-1
aws_cloudFrontBaseUrl: https://xxx.cloudfront.net


recaptcha_siteKey: xxx
recaptcha_secretKey: xxx


jophiel_mailer_host: smt.mailtrap.io
jophiel_mailer_port: 2525
jophiel_mailer_useSsl: false
jophiel_mailer_username: xxx
jophiel_mailer_password: xxx
jophiel_mailer_sender: xxx@yyy.com

jophiel_userAvatar_fs_type: local
jophiel_userAvatar_fs_s3BucketName: xxx
jophiel_userRegistration_enabled: false
jophiel_userRegistration_useRecaptcha: false
jophiel_userRegistration_activationEmailTemplate_subject: xxx
jophiel_userRegistration_activationEmailTemplate_body: xxx
jophiel_userResetPassword_enabled: false
jophiel_userResetPassword_requestEmailTemplate_subject: xxx
jophiel_userResetPassword_requestEmailTemplate_body: xxx
jophiel_userResetPassword_resetEmailTemplate_subject: xxx
jophiel_userResetPassword_resetEmailTemplate_body: xxx


sandalphon_play_crypto_secret: xxx
sandalphon_uriel_secret: xxx
sandalphon_jerahmeel_secret: xxx
sandalphon_gabriel_secret: xxx


sealtiel_sandalphon_secret: xxx
sealtiel_uriel_secret: xxx
sealtiel_gabriel_secret: xxx
sealtiel_jerahmeel_secret: xxx


uriel_submission_fs_type: local
uriel_submission_fs_s3BucketName: xxx
uriel_file_fs_type: local
uriel_file_fs_s3BucketName: xxx


jerahmeel_play_crypto_secret: jxxx
jerahmeel_submission_fs_aws: false
jerahmeel_submission_fs_s3BucketName: xxx


rabbitmq_mgmt_username: xxx
rabbitmq_mgmt_password: xxx
