- block:
  - name: Create gabriel container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/gabriel/var
      - /judgels/gabriel/var/conf
      - /judgels/gabriel/var/data

  - name: Generate gabriel config
    template:
      src: "{{ playbook_dir }}/../conf/gabriel.yml.j2"
      dest: /judgels/gabriel/var/conf/gabriel.yml

  - name: Generate gabriel launcher config
    template:
      src: "{{ playbook_dir }}/../conf/gabriel-launcher.yml.j2"
      dest: /judgels/gabriel/var/conf/launcher-custom.yml

  - name: Pull gabriel image
    docker_image:
      name: "{{ gabriel_image }}"
      force: yes

  - name: Run a gabriel container
    docker_container:
      name: gabriel
      image: "{{ gabriel_image }}"
      privileged: yes
      restart: yes
      restart_policy: always
      log_driver: json-file
      log_options:
        max-size: 256m
        max-file: "2"
      network_mode: host
      volumes:
        - "/judgels/gabriel/var:/judgels/gabriel/var"
        - "/judgels/sandalphon/var:/judgels/sandalphon/var"
