- block:
  - name: Create jophiel container mount volume
    file:
      path: "{{ item }}"
      state: directory
      mode: "0777"
    with_items:
      - /judgels/jophiel/var
      - /judgels/jophiel/var/conf
      - /judgels/jophiel/var/data

  - name: Generate jophiel config
    template:
      src: "{{ playbook_dir }}/../conf/jophiel.yml.j2"
      dest: /judgels/jophiel/var/conf/jophiel.yml

  - name: Generate jophiel launcher config
    template:
      src: "{{ playbook_dir }}/../conf/jophiel-launcher.yml.j2"
      dest: /judgels/jophiel/var/conf/launcher-custom.yml

  - name: Pull jophiel image
    docker_image:
      name: judgels/jophiel
      tag: "{{ judgels_version | default('latest', true) }}"
      force: yes

  - name: Run a jophiel container
    docker_container:
      name: jophiel
      image: "judgels/jophiel:{{ judgels_version | default('latest', true) }}"
      restart: yes
      restart_policy: always
      network_mode: host
      volumes:
        - "/judgels/jophiel/var:/judgels/jophiel/var"
